CREATE TABLE [dbo].[Contacts]
(
	[Id] UNIQUEIDENTIFIER PRIMARY KEY DEFAULT NEWSEQUENTIALID(),
	[ContactName] VARCHAR(200) NOT NULL,
	[ContactEmail] VARCHAR(250) NOT NULL,
	[AddedAt] DATETIME NOT NULL,
	[IsFriendly] BIT NOT NULL,
	[AcceptedAt] DATETIME,
	[IsBlocked] BIT NOT NULL,
	[BlockedAt] DATETIME,
	[ContactStatus] VARCHAR(50) DEFAULT 'Pending' NOT NULL,
	[FK_User] UNIQUEIDENTIFIER FOREIGN KEY REFERENCES [Users](Id) NOT NULL,
	[FK_Contact] UNIQUEIDENTIFIER FOREIGN KEY REFERENCES [Users](Id) NOT NULL
)
