CREATE TABLE [dbo].[Friendly]
(
	[Id] UNIQUEIDENTIFIER PRIMARY KEY DEFAULT NEWSEQUENTIALID(),
	[AddedAt] DATETIME NOT NULL,
	[RemovedAt] DATETIME,
	[FriendlyStatus] VARCHAR(50) DEFAULT 'Pending',
	[FK_User] UNIQUEIDENTIFIER FOREIGN KEY REFERENCES [Users](Id) NOT NULL,
	[Fk_Contact] UNIQUEIDENTIFIER FOREIGN KEY REFERENCES [Contacts] NOT NULL
)
