CREATE TABLE [dbo].[Profiles]
(
	[Id] UNIQUEIDENTIFIER PRIMARY KEY DEFAULT NEWSEQUENTIALID(),
	[ProfileDescription] VARCHAR(MAX) NOT NULL,
	[FK_User] UNIQUEIDENTIFIER FOREIGN KEY REFERENCES [Users](Id) NOT NULL
)
