services:
  api:
    build:
      context: .
      dockerfile: API.partonair/Dockerfile
    ports:
      - "5000:80"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:80 
      - ConnectionStrings__DefaultConnection=Server=db;Database=partonair;User=sa;Password=YourStrong@Passw0rd;TrustServerCertificate=True;Encrypt=False;MultipleActiveResultSets=True
    depends_on:
      db:
        condition: service_healthy
    networks:
      - partonair-network
    restart: unless-stopped

  db:
    build:
      context: ./Database.partonair
      dockerfile: Dockerfile
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=YourStrong@Passw0rd
      - MSSQL_PID=Express
    ports:
      - "1433:1433"
    volumes:
      - db-data:/var/opt/mssql
      - ./Database.partonair/Scripts:/scripts
    networks:
      - partonair-network
    healthcheck:
      test: /opt/mssql-tools/bin/sqlcmd -S localhost -U sa -P "YourStrong@Passw0rd" -Q "SELECT 1" || exit 1
      interval: 10s
      timeout: 10s
      retries: 12
      start_period: 20s
    restart: unless-stopped

networks:
  partonair-network:
    driver: bridge

volumes:
  db-data: