services:
  api:
    build:
      context: .
      dockerfile: API.partonair/Dockerfile
    ports:
      - "5000:80"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:80 
      - ConnectionStrings__DefaultConnection=Server=db;Database=partonair;User=sa;Password=YourStrong@Passw0rd;TrustServerCertificate=True
    depends_on:
      - db
    networks:
      - partonair-network

  db:
    build:
        context: ./Database.partonair
        dockerfile: Dockerfile
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=YourStrong@Passw0rd
      - MSSQL_PID=Express
    ports:
      - "1433:1433"
    volumes:
      - db-data:/var/opt/mssql
      - ./Database.partonair/Scripts:/scripts
      - ./init.sh:/docker-entrypoint-initdb.d/init.sh
    networks:
      - partonair-network

networks:
  partonair-network:
    driver: bridge

volumes:
  db-data: